---
title: "Gene ontology enrichment"
author: "Konstantinos Mechteridis"
date: "1/30/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("topGO")
library("AnnotationFuncs")
library("org.Hs.eg.db")
library("Rgraphviz")
library("knitr")
library("visNetwork")
library("gplots")
library("RColorBrewer")
library("tidyverse")
library("VennDiagram")
library("flavin")
```
## Load data
```{r loadData}
indicator_matrix <- readRDS("use_case_data/geo_data/data/indicator_matrix_lfc1_p0,001.rds")
pathwaysoi_ines <- readRDS(file = "use_case_data/geo_data/comparison/selected_ines_pathways.rds")
pathwaysoi_glone <- readRDS(file = "use_case_data/geo_data/comparison/selected_glone_pathways.rds")
```

## Select pathway of interest
```{r pathwayoii}
pathway <- pathwaysoi_ines$`K-8-L1-10-union`
```
## Visualize pathway
```{r visualize_pathway}
edges <- data.frame(from = pathway@edges$source, to = pathway@edges$target)
nodes <- data.frame(
  id = pathway@nodes$node,
  label = pathway@nodes$node,
  title = paste('<a target="_blank" href = "https://www.ncbi.nlm.nih.gov/gene/?term=',
    pathway@nodes$node, '">Gene id: ', pathway@nodes$node, " (Visit NCBI)</a>",
    sep = ""
  )
)
nodes <- cbind(nodes, group = as.character(pathway@nodes$exception))


network <- visNetwork(
  main = "K-8-L1-10 union network",
  submain = paste0(
    "Nodes: ", nrow(nodes),
    ", Edges: ", nrow(edges),
    "<br>Exception nodes: ", table(nodes$group)["TRUE"],
    "<br>Avg. de cases per node: ", pathway@avg_exp
  ),
  nodes = nodes,
  edges = edges
) %>%
  visGroups(
    groupname = "TRUE",
    color = "#fb8500",
    shape = "square",
    shadow = list(enabled = TRUE)
  ) %>%
  visGroups(groupname = "FALSE", color = "#023e8a") %>%
  visNodes(labelHighlightBold = TRUE)
visSave(network, "union_network.html", selfcontained = TRUE, background = "white")
```

## Heatmap
```{r heatmap}
pathway_data <- pathway@nodes # [pathway@nodes$exception]
lfc_2_matrix <- readRDS("use_case_data/geo_data/data/log_2_fc_tibble.rds")
# Select LFC values for nodes of interest
lfc_2_matrix <- lfc_2_matrix[lfc_2_matrix$hgnc_symbol %in% pathway_data$node, ] %>% column_to_rownames("hgnc_symbol")
# Remove nodes that are not in the dataset
pathway_data <- pathway_data[!pathway_data$node %in% setdiff(pathway_data$node, row.names(lfc_2_matrix)), ]
# Rename comparison so that they fit in the heatmap
colnames(lfc_2_matrix) <- gsub(x = colnames(lfc_2_matrix), pattern = "SARS-CoV-2 versus Mock infected ", replacement = "")
colnames(lfc_2_matrix) <- gsub(x = colnames(lfc_2_matrix), pattern = "SARS-CoV-2 versus Healthy lung ", replacement = "Lung ")
colnames(lfc_2_matrix) <- gsub(x = colnames(lfc_2_matrix), pattern = "SARS-CoV-2 versus Negative control ", replacement = "")
colnames(lfc_2_matrix)[8] <- "HESC cardiomyocytes cells"
colnames(lfc_2_matrix)[11] <- "HPSC colonic organoids"
# Color palette for heatmap
mypalette <- brewer.pal(11, "RdYlBu")
morecols <- colorRampPalette(mypalette)

png("plots_and_figures/geo/LFC1_P0,001/heatmaps/all_genes.png", width = 5 * 300, height = 5 * 300, res = 300, pointsize = 8)
heatmap.2(
  x = as.matrix(lfc_2_matrix),
  density.info = "none",
  notecol = "green",
  col = rev(morecols(50)),
  trace = "none",
  key.xlab = "Log2 fold change",
  RowSideColors = c(ifelse(pathway_data$exception, "#fb8500", "#023e8a")),
  ColSideColors = c(rep("#FFFC5C", 6), "#3C91E6", rep("#FFFC5C", 4), rep("#3C91E6", 3), rep("#FFFC5C", 3), "#3C91E6", "#FFFC5C"),
  margins = c(12, 5)
)
dev.off()
```

## Gene ontology enrichment analysis
### Gene to GO mapping
```{r annotation}
gene_universe <- indicator_matrix$hgnc_symbol
GOs <- translate(gene_universe, from = org.Hs.egALIAS2EG, to = org.Hs.egGO)
myIntersetingGenes <- pathway@nodes$node

geneList <- factor(as.integer(gene_universe %in% myIntersetingGenes))
names(geneList) <- gene_universe
```
### Biological process
```{r bp}
go_data_bp <- new("topGOdata", ontology = "BP", allGenes = geneList, annot = annFUN.gene2GO, gene2GO = GOs)
# Run enrichment tests
classic_fs_bp <- runTest(go_data_bp, algorithm = "classic", statistic = "fisher")
# Save in table
table_bp <- GenTable(go_data_bp, topNodes = 2000, classicFisher = classic_fs_bp)
kable(table_bp)
# Subgraph of the top 10 GO terms
pdf(file = "plots_and_figures/geo/LFC1_P0,001/go_enrichment/dag_top10_enriched_go_terms_bp.pdf")
showSigOfNodes(go_data_bp, score(classic_fs_bp), firstSigNodes = 10, useInfo = "all")
dev.off()

# Save data
write.table(table_bp, file = "use_case_data/geo_data/go_enrichment/top20_enriched_go_terms_bp.tsv", row.names = F, quote = FALSE, sep = "\t")
```
### Molecular function
```{r mf}
go_data_mf <- new("topGOdata", ontology = "MF", allGenes = geneList, annot = annFUN.gene2GO, gene2GO = GOs)
# Run enrichment tests
classic_fs_mf <- runTest(go_data_mf, algorithm = "classic", statistic = "fisher")
# Save in table
table_mf <- GenTable(go_data_mf, classicFisher = classic_fs_mf, orderBy = "classicFisher", topNodes = 20)
kable(table_mf)
# Subgraph of the top 10 GO terms
pdf(file = "plots_and_figures/geo/LFC1_P0,001/go_enrichment/dag_top10_enriched_go_terms_mf.pdf")
showSigOfNodes(go_data_mf, score(classic_fs_mf), firstSigNodes = 10, useInfo = "all")
dev.off()
# Save data
write.table(table_mf, file = "use_case_data/geo_data/go_enrichment/top20_enriched_go_terms_mf.tsv", row.names = F, quote = FALSE, sep = "\t")
```
### Cellular compartment
```{r cc}
go_data_cc <- new("topGOdata", ontology = "CC", allGenes = geneList, annot = annFUN.gene2GO, gene2GO = GOs)
# Run enrichment tests
classic_fs_cc <- runTest(go_data_cc, algorithm = "classic", statistic = "fisher")
# Save in table
table_cc <- GenTable(go_data_cc, classicFisher = classic_fs_cc, orderBy = "classicFisher", topNodes = 20)
kable(table_cc)
# Subgraph of the top 10 GO terms
pdf(file = "plots_and_figures/geo/LFC1_P0,001/go_enrichment/dag_top10_enriched_go_terms_cc.pdf")
showSigOfNodes(go_data_cc, score(classic_fs_cc), firstSigNodes = 10, useInfo = "all")
dev.off()
# Save data
write.table(table_cc, file = "use_case_data/geo_data/go_enrichment/top20_enriched_go_terms_cc.tsv", row.names = F, quote = FALSE, sep = "\t")
```

## Euler diagramms 
```{r venn}
# Get all Go terms with a p value lower than 0.001 ####
bp_terms <- names(classic_fs_bp@score[classic_fs_bp@score < 0.01])
cc_terms <- names(classic_fs_cc@score[classic_fs_cc@score < 0.01])
mf_terms <- names(classic_fs_mf@score[classic_fs_mf@score < 0.01])

# Proposed GO terms from Gene ontology ###
go <- read_gaf(filepath = "use_case_data/geo_data/gaf/sars-cov-2_targets.gaf") %>% select(GO_ID = "GO_ID", Aspect = "Aspect")
go_bp <- go[go$Aspect == "P", ]$GO_ID
go_cc <- go[go$Aspect == "C", ]$GO_ID
go_mf <- go[go$Aspect == "F", ]$GO_ID

# Euler diagram bp
# Generate 3 sets of 200 words
set1 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")
set2 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")
set3 <- paste(rep("word_" , 200) , sample(c(1:1000) , 200 , replace=F) , sep="")

# Prepare a palette of 3 colors with R colorbrewer:
myCol <- c("#347FC4","#F1A66A")

futile.logger::flog.threshold(futile.logger::ERROR, name = "VennDiagramLogger")
# Euler BP ####
venn.diagram(x = list(bp_terms, go_bp), category.names = c("M-A" , "GO"), filename = 'plots_and_figures/geo/LFC1_P0,001/euler/euler_bp.png',
        # Output features
          imagetype = "png",
          height = 1200,
          width = 1300,
          resolution = 600,
          compression = "lzw",
        # Circles
          lwd = 2,
          lty = 'blank',
          fill = myCol,
        # Numbers
          cex = .9,
          fontface = "bold",
          fontfamily = "Helvetica",
        # Set names
          cat.cex = 0.9,
          cat.fontface = "bold",
          cat.default.pos = "outer",
          cat.pos = c(-27, 27),
          cat.dist = c(0.055, 0.055),
          cat.col = myCol, 
        # Title
          main.fontfamily = "Helvetica",
          main = "BP GO terms related to SARS-Cov-2 vs.\n Meta-Analysis terms with p-val < 0.01",
          main.cex = 0.6)


# Euler MF ####
venn.diagram(x = list(mf_terms, go_mf), category.names = c("M-A" , "GO"), filename = 'plots_and_figures/geo/LFC1_P0,001/euler/euler_mf.png',
        # Output features
          imagetype = "png",
          height = 1200,
          width = 1300,
          resolution = 600,
          compression = "lzw",
        # Circles
          lwd = 2,
          lty = 'blank',
          fill = myCol,
        # Numbers
          cex = .9,
          fontface = "bold",
          fontfamily = "Helvetica",
        # Set names
          cat.cex = 0.9,
          cat.fontface = "bold",
          cat.default.pos = "outer",
          cat.pos = c(-18, 40),
          cat.dist = c(0.040, 0.040),
          cat.col = myCol, 
        # Title
          main.fontfamily = "Helvetica",
          main = "MF GO terms related to SARS-Cov-2 vs.\n Meta-Analysis terms with p-val < 0.01",
          main.cex = 0.6)


# Euler CC ####
venn.diagram(x = list(cc_terms, go_cc), category.names = c("M-A" , "GO"), filename = 'plots_and_figures/geo/LFC1_P0,001/euler/euler_cc.png',
        # Output features
          imagetype = "png",
          height = 1200,
          width = 1300,
          resolution = 600,
          compression = "lzw",
        # Circles
          lwd = 2,
          lty = 'blank',
          fill = myCol,
        # Numbers
          cex = .9,
          fontface = "bold",
          fontfamily = "Helvetica",
        # Set names
          cat.cex = 0.9,
          cat.fontface = "bold",
          cat.default.pos = "outer",
          cat.pos = c(-18, 40),
          cat.dist = c(0.040, 0.040),
          cat.col = myCol, 
        # Title
          main.fontfamily = "Helvetica",
          main = "CC GO terms related to SARS-Cov-2 vs.\n Meta-Analysis terms with p-val < 0.01",
          main.cex = 0.6)
```
